# Generated by Django 5.2.17 on 2026-09-09 13:39

import django.core.validators
import django.db.models.deletion
import events.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160, unique=True, validators=[django.core.validators.RegexValidator(message='Use a lowercase slug containing letters, numbers, and single hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('title_sq', models.CharField(blank=True, max_length=160, validators=[events.validators.validate_plain_text])),
                ('title_en', models.CharField(blank=True, max_length=160, validators=[events.validators.validate_plain_text])),
                ('summary_sq', models.CharField(blank=True, max_length=240, validators=[events.validators.validate_plain_text])),
                ('summary_en', models.CharField(blank=True, max_length=240, validators=[events.validators.validate_plain_text])),
                ('description_sq', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000), events.validators.validate_plain_text])),
                ('description_en', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000), events.validators.validate_plain_text])),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('doors_at', models.DateTimeField(blank=True, null=True)),
                ('lineup', models.JSONField(blank=True, default=list, validators=[events.validators.validate_lineup])),
                ('poster', models.FileField(blank=True, upload_to='', validators=[events.validators.validate_poster_extension])),
                ('poster_480', models.FileField(blank=True, editable=False, upload_to='')),
                ('poster_960', models.FileField(blank=True, editable=False, upload_to='')),
                ('poster_1440', models.FileField(blank=True, editable=False, upload_to='')),
                ('poster_social', models.FileField(blank=True, editable=False, upload_to='')),
                ('poster_metadata', models.JSONField(blank=True, default=dict, editable=False)),
                ('poster_alt_sq', models.CharField(blank=True, max_length=240, validators=[events.validators.validate_plain_text])),
                ('poster_alt_en', models.CharField(blank=True, max_length=240, validators=[events.validators.validate_plain_text])),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('event_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('entry_note_sq', models.CharField(blank=True, max_length=240, validators=[events.validators.validate_plain_text])),
                ('entry_note_en', models.CharField(blank=True, max_length=240, validators=[events.validators.validate_plain_text])),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'title_sq'],
                'constraints': [models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='event_ends_after_start'), models.CheckConstraint(condition=models.Q(('doors_at__isnull', True), ('starts_at__isnull', True), ('doors_at__lte', models.F('starts_at')), _connector='OR'), name='event_doors_not_after_start'), models.CheckConstraint(condition=models.Q(('is_featured', False), models.Q(('event_status__in', ['scheduled', 'postponed']), ('publication_status', 'published')), _connector='OR'), name='event_featured_state_valid'), models.UniqueConstraint(condition=models.Q(('event_status__in', ['scheduled', 'postponed']), ('is_featured', True), ('publication_status', 'published')), fields=('is_featured',), name='one_published_featured_event')],
            },
        ),
    ]
