# Generated by Django 5.2.17 on 2026-09-09 13:39

from django.db import migrations


def create_event_editors_group(apps, schema_editor):
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")
    content_type, _ = content_type_model.objects.get_or_create(app_label="events", model="event")
    group, _ = group_model.objects.get_or_create(name="Event editors")
    permissions = []
    for action in ("add", "change", "delete", "view"):
        permission, _ = permission_model.objects.get_or_create(
            content_type=content_type,
            codename=f"{action}_event",
            defaults={"name": f"Can {action} event"},
        )
        permissions.append(permission)
    group.permissions.set(permissions)


def delete_event_editors_group(apps, schema_editor):
    apps.get_model("auth", "Group").objects.filter(name="Event editors").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_event_editors_group, delete_event_editors_group),
    ]
