# Generated by Django 5.2.17 on 2026-09-09 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_create_event_editors_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("publication_status", "draft"),
                    models.Q(
                        models.Q(("title_sq", ""), _negated=True),
                        models.Q(("title_en", ""), _negated=True),
                        models.Q(("summary_sq", ""), _negated=True),
                        models.Q(("summary_en", ""), _negated=True),
                        models.Q(("description_sq", ""), _negated=True),
                        models.Q(("description_en", ""), _negated=True),
                        ("starts_at__isnull", False),
                        ("ends_at__isnull", False),
                        models.Q(("poster", ""), _negated=True),
                        models.Q(("poster_metadata", {}), _negated=True),
                        ("published_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="event_published_content_complete",
            ),
        ),
    ]
